# Generated by Django 6.0.4 on 2026-04-17 14:03

import django.db.models.deletion
import listing_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=listing_api.models.generate_api_key, max_length=80, unique=True)),
                ('organization', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(default=30)),
                ('rate_limit_per_day', models.IntegerField(default=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API'), ('demo', 'Demo')], default='api', max_length=20)),
                ('image_count', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, default='', max_length=80)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('embeddings_included', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='listing_api.apikey')),
            ],
            options={
                'verbose_name': 'Analysis Request',
                'verbose_name_plural': 'Analysis Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
