# Generated by Django 5.2.1 on 2025-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstyleprofile',
            name='archetypes',
        ),
        migrations.AddField(
            model_name='userstyleprofile',
            name='style_identity',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userstyleprofile',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
