# Generated by Django 5.2.1 on 2025-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_data', '0002_remove_userstyleprofile_archetypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstyleprofile',
            name='style_archetype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
