# Generated by Django 5.2.1 on 2025-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_data', '0003_userstyleprofile_style_archetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystyleinput',
            name='outfit_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
