# Generated by Django 5.2.1 on 2025-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_data', '0004_dailystyleinput_outfit_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystyleinput',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
