# Generated by Django 5.2.1 on 2025-07-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle_data', '0007_wardrobeitem_is_favorite_wardrobeitem_last_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='visual_descriptors',
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='style_tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
